config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'homes#top'
  get 'homes/about' => 'homes#about'

  resources :users, only: %i[show edit update]

  resources :invites do
    resource :invite_comments, only: %i[create destroy]
    resource :marks, only: %i[create destroy]
  end

  resources :posts do
    resource :post_comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
  end

  resources :notifications, only: %i[index destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/invite.rb
class Invite < ApplicationRecord
  enum sex: {
    "未選択": 0, "オス": 1, "メス": 2
  }, _prefix: true

  enum age: {
    "未選択": 0, "子猫": 1, "成猫": 2, "老猫": 3
  }, _prefix: true

  enum type: {
    "未選択": 0, "白": 1, "黒": 2, "グレー": 3, "三毛猫": 4, "茶トラ": 5, "キジトラ": 6, "サバトラ": 7, "サビ": 8, "白黒": 9,
    "グレー白": 10, "茶白": 11, "キジ白": 12, "サバ白": 13, "その他": 14
  }, _prefix: true
  # [type]カラムでエラーが出るのを防ぐために記載
  self.inheritance_column = :_type_disabled

  belongs_to :user
  has_many :tags, dependent: :destroy
  attachment :image
  has_many :invite_comments, dependent: :destroy
  has_many :marks, dependent: :destroy

  def marked_by?(user, invite)
    marks.where(user_id: user.id, invite_id: invite.id).size > 0
  end
  # mount_uploader :video, VideoUploader
  # mount_uploader :image_id, ImageUploader

  has_many :notifications, dependent: :destroy
  # 気になる通知の処理
  def create_notification_favorite!(current_user)
    temp = Notification.where(['visitor_id = ? and visited_id = ? and invite_id = ? and action = ? ', current_user.id, user_id, id, 'mark'])
    # blank? = 一度も気になるされていない場合で気になるをされたら通知する
    if temp.blank?
      notification = current_user.active_notifications.new(
        invite_id: id,
        visited_id: user_id,
        action: 'mark'
      )
      # 自分が自分の投稿に気になるをした時は通知済の扱いをする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  # コメント通知の処理
  def create_notification_comment!(current_user, invite_comment_id)
    # （ログイン中の会員と投稿者以外で）同じ投稿にコメントしているユーザーに通知を送る
    temp_ids = InviteComment.where(invite_id: id).where.not('user_id=? or user_id=?', current_user.id, user_id).select(:user_id).distinct
    # 取得したユーザーへの通知レコードを作成
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, invite_comment_id, temp_id['user_id'])
    end
    # 投稿者へ通知を作成
    save_notification_comment!(current_user, invite_comment_id, user_id)
  end

  def save_notification_comment!(current_user, invite_comment_id, visited_id)
    notification = current_user.active_notifications.new(
      invite_id: id,
      invite_comment_id: invite_comment_id,
      visited_id: visited_id,
      action: 'invite_comment'
    )
    # 自分が自分の投稿にコメントした時は通知済の扱いをする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]

  def new
    @invite = Invite.new
  end

  def index
    @q = Invite.ransack(params[:q])
    @invites = @q.result.page(params[:page]).reverse_order
  end

  def show
    @invite = Invite.find(params[:id])
    @invite_comment = InviteComment.new
  end

  def create
    @invite = Invite.new(invite_params)
    @invite.user_id = current_user.id
    @invite.save
    tags = Vision.get_image_data(@invite.image)
    tags.each do |tag|
      @invite.tags.create(name: tag)
    end
    redirect_to user_path(current_user.id), flash: { success: '投稿が完了しました。' }
  end

  def edit
    @invite = Invite.find(params[:id])
  end

  def update
    invite = Invite.find(params[:id])
    invite.update(invite_params)
    invite.tags.delete_all
    tags = Vision.get_image_data(invite.image)
    tags.each do |tag|
      invite.tags.create(name: tag)
    end
    redirect_to invite_path(invite), flash: { success: '変更が完了しました。' }
  end

  def destroy
    invite = Invite.find(params[:id])
    invite.destroy
    redirect_to user_path(current_user.id), flash: { success: '投稿を削除しました。' }
  end

  private

  def invite_params
    params.require(:invite).permit(:title, :content, :sex, :age, :type, :image)
  end
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/views/invites/_comment.html.erb
<!-- コメントの表示 -->
<% invite_comments.each do |invite_comment| %>
	<div class="comment">
		<div><%= invite_comment.comment %></div>
		<span class="is-size-7"><%= link_to invite_comment.user.handle_name, user_path(invite_comment.user.id) %></span>
		<span class="is-size-7"><%= invite_comment.created_at.strftime('%Y/%m/%d') %></span>
		<!-- コメントを投稿したユーザーのみ削除ボタンが表示される -->
		<% if invite_comment.user == current_user %>
			<%= link_to "", invite_invite_comments_path(invite_comment), class: "delete is-small", method: :delete, remote: true, data:{confirm: "コメントを削除しますか？"} %>
		<% end %>
	</div>
<% end %>

app/views/invites/_index.html.erb
<div class="tile is-ancestor">
	<% invites.each do |invite| %>
	<div class=”tile is-parent”>
		<div class="card">
			<div class="card-image">
				<%= link_to invite_path(invite) do %>
					<%= attachment_image_tag invite, :image, :fill, 283, 283, fallback: "no_image.jpg" %>
				<% end %>
			</div>
			<div class="card-content">
				<span class="subtitle is-6">募集タイトル</span>
				<p><%= invite.title %></p>
				<span class="subtitle is-6">猫情報</span>
				<p><%= invite.sex %> ／ <%= invite.age %> ／ <%= invite.type %></p>
				<span class="subtitle is-6">掲載者</span>
				<p><%= link_to invite.user.handle_name, user_path(invite.user.id) %></p>
				<span class="subtitle is-6">掲載日</span>
				<p><%= invite.created_at.strftime('%Y/%m/%d') %></p>
			</div>
		</div>
	</div>
	<% end %>
</div>

app/views/invites/_mark.html.erb
<div class="box is-pulled-right">
	<% if invite.marked_by?(current_user, invite) %>
	<%= link_to invite_marks_path(invite), method: :delete, remote: true do %>
	<i class="fas fa-star" aria-hidden="true" style="color: orange;"></i>
	<%= invite.marks.count %> 気になる
	<% end %>
	<% else %>
	<%= link_to invite_marks_path(invite), method: :post, remote: true do %>
	<i class="far fa-star" aria-hidden="true" style="color: orange;"></i>
	<%= invite.marks.count %> 気になる
	<% end %>
	<% end %>
</div>

app/views/invites/_search_form.html.erb
<div class="box">
	<%= search_form_for q, url:invites_path do |f| %>

	<div class="field is-grouped">
		<%= f.label "性別　", class: "subtitle is-6" %>
		<p class="control">
			<%= f.radio_button :sex_eq, '', {:checked => true}%>
			<%= f.label "指定しない" %>
			<%= f.radio_button :sex_eq, 0 %>
			<%= f.label :sex, "未選択", {value: :未選択} %>
			<%= f.radio_button :sex_eq, 1 %>
			<%= f.label :sex_, "オス", {value: :オス} %>
			<%= f.radio_button :sex_eq, 2 %>
			<%= f.label :sex, "メス", {value: :メス} %>
		</p>
	</div>

	<div class="field is-grouped">
		<%= f.label "年齢　", class: "subtitle is-6" %>
		<p class="control">
			<%= f.radio_button :age_eq, '', {:checked => true}%>
			<%= f.label "指定しない" %>
			<%= f.radio_button :age_eq, 0 %>
			<%= f.label :age, "未選択", {value: :未選択} %>
			<%= f.radio_button :age_eq, 1 %>
			<%= f.label :age, "子猫", {value: :子猫} %>
			<%= f.radio_button :age_eq, 2 %>
			<%= f.label :age, "成猫", {value: :成猫} %>
			<%= f.radio_button :age_eq, 3 %>
			<%= f.label :age, "老猫", {value: :老猫} %>
		</p>
	</div>

	<div class="field is-grouped">
		<%= f.label "種類", class: "subtitle is-6" %>
		<p class="control">
			<div class="select">
				<%= f.select :type_eq, Invite.types, :include_blank => '指定しない' %>
			</div>
		</p>
	</div>

	<div class="actions">
		<%= f.submit "検索", class: "button is-info" %>
	</div>

	<% end %>
</div>

app/views/invites/edit.html.erb
<h1 class="title is-1 has-text-primary">募集内容変更ページ</h1>

<!-- エラーあれば件数を表示 -->
<% if @invite.errors.any? %>
<div id="error_explanation">
  <h2><%= @invite.errors.count %>件のエラーが発生しました。</h2>
  <ul>
    <% @invite.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="box">
  <%= form_for(@invite) do |f| %>

  <div class="field">
    <%= f.label "写真ファイル" %>
    <%= attachment_image_tag @invite, :image, :fill, 700, 450, fallback: "no_image.jpg" %>
    <%= f.attachment_field :image %>
  </div>

  <div class="field">
    <p class="control">
      <%= f.label "募集タイトル" %>
      <%= f.text_field :title, autofocus: true, class: "input", placeholder: "（例：甘えん坊な茶トラくん）", autocomplete: "title" %>
    </p>
  </div>

  <div class="field">
    <p class="control">
      <%= f.label "募集内容" %>
      <%= f.text_area :content, autofocus: true, class: "input", placeholder: "（例：庭に迷い込んだところを保護しました。）", autocomplete: "content" %>
    </p>
  </div>

  <div class="field">
    <%= f.label "性別" %>
    <p class="control">
      <%= f.radio_button :sex, :未選択 %>
      <%= f.label :sex, "未選択", {value: :未選択} %>
      <%= f.radio_button :sex, :オス %>
      <%= f.label :sex, "オス", {value: :オス} %>
      <%= f.radio_button :sex, :メス %>
      <%= f.label :sex, "メス", {value: :メス} %>
    </p>
  </div>

  <div class="field">
    <%= f.label "年齢" %>
    <p class="control">
      <%= f.radio_button :age, :未選択 %>
      <%= f.label :age, "未選択", {value: :未選択} %>
      <%= f.radio_button :age, :子猫 %>
      <%= f.label :age, "子猫", {value: :子猫} %>
      <%= f.radio_button :age, :成猫 %>
      <%= f.label :age, "成猫", {value: :成猫} %>
      <%= f.radio_button :age, :老猫 %>
      <%= f.label :age, "老猫", {value: :老猫} %>
    </p>
  </div>

  <div class="field">
    <%= f.label "種類" %>
    <p class="control">
      <div class="select">
        <%= f.select :type, Invite.types.keys, {} %>
      </div>
    </p>
  </div>

  <div class="actions">
    <%= f.submit "変更内容を保存する", class: "button is-success" %>
  </div>
  <% end %>
</div>

app/views/invites/index.html.erb
<h1 class="title is-1 has-text-primary">募集一覧ページ</h1>

<!-- 検索フォーム -->
<%= render 'invites/search_form', q: @q %>

<!-- 募集一覧or検索結果表示 -->
<%= render 'invites/index', invites: @invites %>

<%= paginate @invites, class: "paginate" %>

app/views/invites/new.html.erb
<h1 class="title is-1 has-text-primary">新規募集ページ</h1>

<!-- エラーあれば件数を表示 -->
<% if @invite.errors.any? %>
<div id="error_explanation">
  <h2><%= @invite.errors.count %>件のエラーが発生しました。</h2>
  <ul>
    <% @invite.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="box">
  <%= form_for(@invite, url: invites_path) do |f| %>

  <div class="field">
    <%= f.label "写真ファイル" %>
    <%= attachment_image_tag @invite, :image, :fill, fallback: "no_image.jpg", size:'300x200' %>
    <%= f.attachment_field :image %>
  </div>

  <div class="field">
    <p class="control">
      <%= f.label "募集タイトル" %>
      <%= f.text_field :title, autofocus: true, class: "input", placeholder: "（例：元気いっぱい！茶トラの子猫）", autocomplete: "title" %>
    </p>
  </div>

  <div class="field">
    <p class="control">
      <%= f.label "保護経緯・性格など" %>
      <%= f.text_field :content, autofocus: true, class: "input", placeholder: "（例：母猫とはぐれて鳴いていたところを保護しました。とても甘えん坊です。）", autocomplete: "content" %>
    </p>
  </div>

  <div class="field">
   <%= f.label "性別" %>
   <p class="control">
     <%= f.radio_button :sex, :未選択 %>
     <%= f.label :sex, "未選択", {value: :未選択} %>
     <%= f.radio_button :sex, :オス %>
     <%= f.label :sex, "オス", {value: :オス} %>
     <%= f.radio_button :sex, :メス %>
     <%= f.label :sex, "メス", {value: :メス} %>
   </p>
 </div>

 <div class="field">
   <%= f.label "年齢" %>
   <p class="control">
     <%= f.radio_button :age, :未選択 %>
     <%= f.label :age, "未選択", {value: :未選択} %>
     <%= f.radio_button :age, :子猫 %>
     <%= f.label :age, "子猫", {value: :子猫} %>
     <%= f.radio_button :age, :成猫 %>
     <%= f.label :age, "成猫", {value: :成猫} %>
     <%= f.radio_button :age, :老猫 %>
     <%= f.label :age, "老猫", {value: :老猫} %>
   </p>
 </div>

 <div class="field">
   <%= f.label "種類" %>
   <p class="control">
     <div class="select">
       <%= f.select :type, Invite.types.keys, {} %>
     </div>
   </p>
 </div>

 <div class="actions">
  <%= f.submit "募集を開始する" , class: "button is-success" %>
</div>

<% end %>
</div>

app/views/invites/show.html.erb
<h1 class="title is-1 has-text-primary">募集詳細ページ</h1>

<div class="tile is-ancestor">
	<div class="tile is-parent">
		<!-- 画像表示 -->
		<div class="tile is-child box">
			<%= attachment_image_tag @invite, :image, :fill, 700, 450, fallback: "no_image.jpg" %>
			<div class="tag-box">
				<% @invite.tags.each do |tag| %>
  				<span class="label"><%= tag.name %></span>
				<% end %>
			</div>
			<!-- ログイン時のみ気になるボタン表示 -->
			<% if user_signed_in? %>
			<div id="invite-<%= @invite.id %>">
				<%= render partial: "invites/mark", locals: { invite: @invite } %>
			</div>
			<% end %>
			<!-- 募集情報 -->
			<span class="subtitle is-6">募集タイトル</span>
			<p><%= @invite.title %></p>
			<span class="subtitle is-6">内容</span>
			<p><%= @invite.content %></p>
			<span class="subtitle is-6">猫情報</span>
			<p><%= @invite.sex %> ／ <%= @invite.age %> ／ <%= @invite.type %></p>
			<span class="subtitle is-6">募集開始日</span>
			<p><%= @invite.created_at.strftime('%Y/%m/%d') %></p>
			<!-- ログインしている会員の場合のみ編集と削除ボタンを表示 -->
			<% if @invite.user == current_user %>
			<hr>
			<%= link_to "内容を変更する", edit_invite_path(@invite), class: "button is-success" %>
			<%= link_to "この募集を削除する", invite_path(@invite), class: "button is-danger", method: :delete, data:{confirm: "本当に消しますか？"} %>
			<% end %>
		</div>
	</div>
	<div class="tile is-parent">
		<div class="tile is-child">
			<!-- 掲載者情報ここから -->
			<h4 class="subtitle is-3">掲載者情報</h4>
			<span class="subtitle is-6">ハンドルネーム</span>
			<p><%= link_to @invite.user.handle_name, user_path(@invite.user.id) %></p>
			<span class="subtitle is-6">自己紹介文</span>
			<p><%= @invite.user.profile %></p>
			<span class="subtitle is-6">住所</span>
			<p><%= @invite.user.prefecture %></p>
			<!-- 掲載者情報ここまで -->
			<hr>
			<!-- コメント欄ここから -->
			<h4 class="subtitle is-3">コメント欄</h4>
			<div id="comment_<%= @invite.id %>">
				<%= render 'invites/comment', invite_comments: @invite.invite_comments %>
			</div>
			<!-- ログイン時はコメント入力フォーム表示 -->
			<% if user_signed_in? %>
			<div class="comment_form">
				<%= form_with(model: [@invite, @invite_comment], remote: true) do |f| %>
				<%= f.text_area :comment, class: "textarea",placeholder: "掲載者への質問はこちらへ" %>
				<%= f.submit "コメントを送信する", class: "button is-info is-pulled-right" %>
				<% end %>
			</div>
			<!-- 未ログイン時はメッセージを表示 -->
			<% else %>
			<div class="box">
				<p>
					コメントの投稿は会員のみが利用できます。<br>
					新規会員登録は<%= link_to "こちら", "/users/sign_up" %>から。
				</p>
			</div>
			<% end %>
			<!-- コメント欄ここまで -->
		</div>
	</div>
</div>