config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'homes#top'
  get 'homes/about' => 'homes#about'

  resources :users, only: %i[show edit update]

  resources :invites do
    resource :invite_comments, only: %i[create destroy]
    resource :marks, only: %i[create destroy]
  end

  resources :posts do
    resource :post_comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
  end

  resources :notifications, only: %i[index destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum prefecture: {
    "---未選択---": 0, 北海道: 1, 青森県: 2, 岩手県: 3, 宮城県: 4, 秋田県: 5, 山形県: 6, 福島県: 7,
    茨城県: 8, 栃木県: 9, 群馬県: 10, 埼玉県: 11, 千葉県: 12, 東京都: 13, 神奈川県: 14,
    新潟県: 15, 富山県: 16, 石川県: 17, 福井県: 18, 山梨県: 19, 長野県: 20,
    岐阜県: 21, 静岡県: 22, 愛知県: 23, 三重県: 24,
    滋賀県: 25, 京都府: 26, 大阪府: 27, 兵庫県: 28, 奈良県: 29, 和歌山県: 30,
    鳥取県: 31, 島根県: 32, 岡山県: 33, 広島県: 34, 山口県: 35,
    徳島県: 36, 香川県: 37, 愛媛県: 38, 高知県: 39,
    福岡県: 40, 佐賀県: 41, 長崎県: 42, 熊本県: 43, 大分県: 44, 宮崎県: 45, 鹿児島県: 46, 沖縄県: 47
  }

  # 募集
  has_many :invites, dependent: :destroy
  has_many :invite_comments, dependent: :destroy
  has_many :marks, dependent: :destroy

  # 投稿
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # 通知
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[edit update]
  def show
    @user = User.find(params[:id])
    @invites = @user.invites.page(params[:page]).reverse_order
    @posts = @user.posts.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :handle_name, :profile, :prefecture, :email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1 class="title is-1 has-text-primary">会員情報変更ページ</h1>

<div class="box">
<%= form_for(@user) do |f| %>
  <p class="has-text-success">公開される情報です。</p>

  <div class="field">
    <p class="control">
      <%= f.label "ハンドルネーム" %>
      <%= f.text_field :handle_name, autofocus: true, class: "input", placeholder: "（例：ねこ子）", autocomplete: "handle_name" %>
    </p>
  </div>

  <div class="field">
    <p class="control">
      <%= f.label "自己紹介文" %>
      <%= f.text_field :profile, autofocus: true, class: "input", placeholder: "（例：2匹の猫と暮らす学生です。）", autocomplete: "profile" %>
    </p>
  </div>

  <div class="field">
    <p class="control">
      <%= f.label "住所（都道府県を選択してください）" %>
      <div class="select">
      <%= f.select :prefecture, User.prefectures.keys, {} %>
      </div>
    </p>
  </div>

  <hr>

  <p class="has-text-success">以下の情報は他の会員には公開されません。</p>

  <div class="field">
    <p class="control">
      <%= f.label "氏名" %>
      <%= f.text_field :name, autofocus: true, class: "input", placeholder: "（例：猫田 里子）", autocomplete: "name" %>
    </p>
  </div>

  <div class="field">
    <p class="control">
      <%= f.label "メールアドレス" %>
      <%= f.email_field :email, autofocus: true, class: "input", placeholder: "（例：neko@test.co.jp）", autocomplete: "email" %>
    </p>
  </div>

  <div class="actions">
 	<%= f.submit "変更内容を保存する", class: "button is-success" %>
  </div>
<% end %>
</div>

app/views/users/show.html.erb
<h1 class="title is-1 has-text-primary"><%= @user.handle_name %>  さんのページ</h1>

<div class="columns">
  <!-- 会員情報表示欄 -->
 	<div class="column is-one-quarter ">
	<div class="box">
	  <p class="subtitle is-4">会員情報</p>
	  	<span class="subtitle is-6">ハンドルネーム</span>
	  	<p><%= @user.handle_name %></p>
	  	<span class="subtitle is-6">自己紹介文</span>
		<p><%= @user.profile %></p>
		<span class="subtitle is-6">住所</span>
		<p><%= @user.prefecture %></p>
		<!-- 以下、ログインしている会員しか表示しない情報 -->
		<% if user_signed_in? && @user.id == current_user.id %>
		  <hr>
		  <span class="subtitle is-6">氏名</span>
		  <p><%= @user.name %></p>
		  <span class="subtitle is-6">メールアドレス</span>
		  <p><%= @user.email %></p>
		  <br>
		  <p><%= link_to "登録情報変更", edit_user_path(@user), class: "button is-success" %></p>
		<% end %>
	</div>
 	</div>

	<div class="column is-three-quarters ">
	  <!-- 募集一覧 -->
		<p class="subtitle is-3">
			募集掲載中

			<% if user_signed_in? && @user.id == current_user.id %>
			  <%= link_to "募集を出す", new_invite_path, class: "button is-info" %>
			<% end %>
		</p>
		<%= render 'invites/index', invites: @invites %>
		<%= paginate @invites %>
		<hr>
	  <!-- 投稿一覧 -->
		<p class="subtitle is-3">
			投稿
			<% if user_signed_in? && @user.id == current_user.id %>
			  <%= link_to "投稿する", new_post_path, class: "button is-info" %>
			<% end %>
		</p>
		<%= render 'posts/index', posts: @posts %>
		<%= paginate @posts %>
	</div>
</div>