config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'homes#top'
  get 'homes/about' => 'homes#about'

  resources :users, only: %i[show edit update]

  resources :invites do
    resource :invite_comments, only: %i[create destroy]
    resource :marks, only: %i[create destroy]
  end

  resources :posts do
    resource :post_comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
  end

  resources :notifications, only: %i[index destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  enum sex: {
    "未選択": 0, "オス": 1, "メス": 2
  }, _prefix: true

  enum age: {
    "未選択": 0, "子猫": 1, "成猫": 2, "老猫": 3
  }, _prefix: true

  enum type: {
    "未選択": 0, "白": 1, "黒": 2, "グレー": 3, "三毛猫": 4, "茶トラ": 5, "キジトラ": 6, "サバトラ": 7, "サビ": 8, "白黒": 9,
    "グレー白": 10, "茶白": 11, "キジ白": 12, "サバ白": 13, "その他": 14
  }, _prefix: true
  # [type]カラムでエラーが出るのを防ぐために記載
  self.inheritance_column = :_type_disabled

  belongs_to :user
  has_many :tags, dependent: :destroy
  attachment :image
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  # mount_uploader :image_id, ImageUploader

  has_many :notifications, dependent: :destroy

  # いいね通知の処理
  def create_notification_favorite!(current_user)
    temp = Notification.where(['visitor_id = ? and visited_id = ? and post_id = ? and action = ? ', current_user.id, user_id, id, 'favorite'])
    # blank? = 一度もいいねされていない場合でいいねをされたら通知する
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'favorite'
      )
      # 自分が自分の投稿にいいねをした時は通知済の扱いをする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  # コメント通知の処理
  def create_notification_comment!(current_user, post_comment_id)
    # （ログイン中の会員と投稿者以外で）同じ投稿にコメントしているユーザーに通知を送る
    temp_ids = PostComment.where(post_id: id).where.not('user_id=? or user_id=?', current_user.id, user_id).select(:user_id).distinct
    # 取得したユーザーへの通知を作成
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, post_comment_id, temp_id['user_id'])
    end
    # 投稿者へ通知を作成
    save_notification_comment!(current_user, post_comment_id, user_id)
  end

  def save_notification_comment!(current_user, post_comment_id, visited_id)
    notification = current_user.active_notifications.new(
      post_id: id,
      post_comment_id: post_comment_id,
      visited_id: visited_id,
      action: 'post_comment'
    )
    # 自分が自分の投稿にコメントした時は通知済の扱いをする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]

  def new
    @post = Post.new
  end

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result.page(params[:page]).reverse_order
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.save
    tags = Vision.get_image_data(@post.image)
    tags.each do |tag|
      @post.tags.create(name: tag)
    end
    redirect_to user_path(current_user.id), flash: { success: '投稿が完了しました。' }
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    post.tags.delete_all
    tags = Vision.get_image_data(post.image)
    tags.each do |tag|
      post.tags.create(name: tag)
    end
    redirect_to post_path(post), flash: { success: '変更が完了しました。' }
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to user_path(current_user.id), flash: { success: '投稿を削除しました。' }
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :sex, :age, :type, :image)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<!-- コメントの表示 -->
<% post_comments.each do |post_comment| %>
	<div class="comment">
		<div><%= post_comment.comment %></div>
		<span class="is-size-7"><%= link_to post_comment.user.handle_name, user_path(post_comment.user.id) %></span>
		<span class="is-size-7"><%= post_comment.created_at.strftime('%Y/%m/%d') %></span>
		<!-- コメントを投稿したユーザーのみ削除ボタンが表示される -->
		<% if post_comment.user == current_user %>
		<%= link_to "", post_post_comments_path(post_comment), class: "delete is-small", method: :delete, remote: true, data:{confirm: "コメントを削除しますか？"} %>
		<% end %>
	</div>
<% end %>

app/views/posts/_favorite.html.erb
<div class="box is-pulled-right">
	<% if post.favorited_by?(current_user) %>
	<%= link_to post_favorites_path(post), method: :delete, remote: true do %>
	<i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
	<%= post.favorites.count %> いいね
	<% end %>
	<% else %>
	<%= link_to post_favorites_path(post), method: :post, remote: true do %>
	<i class="far fa-heart" aria-hidden="true"  style="color: red;"></i>
	<%= post.favorites.count %> いいね
	<% end %>
	<% end %>
</div>

app/views/posts/_index.html.erb
<div class="tile is-ancestor">
	<% posts.each do |post| %>
	<div class=”tile is-parent”>
		<div class="card">
			<div class="card-image">
				<%= link_to post_path(post) do %>
					<%= attachment_image_tag post, :image, :fill, 283, 283, fallback: "no_image.jpg" %>
				<% end %>
			</div>
			<div class="card-content">
				<span class="subtitle is-6">投稿タイトル</span>
				<p><%= post.title %></p>
				<span class="subtitle is-6">猫情報</span>
				<p><%= post.sex %> ／ <%= post.age %> ／ <%= post.type %></p>
				<span class="subtitle is-6">投稿者</span>
				<p><%= link_to post.user.handle_name, user_path(post.user.id) %></p>
				<span class="subtitle is-6">投稿日</span>
				<p><%= post.created_at.strftime('%Y/%m/%d') %></p>
			</div>
		</div>
	</div>
	<% end %>
</div>

app/views/posts/_search_form.html.erb
<div class="box">
	<%= search_form_for q, url:posts_path do |f| %>

	<div class="field is-grouped">
		<%= f.label "性別　", class: "subtitle is-6" %>
		<p class="control">
			<%= f.radio_button :sex_eq, '', {:checked => true}%>
			<%= f.label "指定しない" %>
			<%= f.radio_button :sex_eq, 0 %>
			<%= f.label :sex_, "未選択", {value: :未選択} %>
			<%= f.radio_button :sex_eq, 1 %>
			<%= f.label :sex_, "オス", {value: :オス} %>
			<%= f.radio_button :sex_eq, 2 %>
			<%= f.label :sex, "メス", {value: :メス} %>
		</p>
	</div>

	<div class="field is-grouped">
		<%= f.label "年齢　", class: "subtitle is-6" %>
		<p class="control">
			<%= f.radio_button :age_eq, '', {:checked => true}%>
			<%= f.label "指定しない" %>
			<%= f.radio_button :age_eq, 0 %>
			<%= f.label :age, "未選択", {value: :未選択} %>
			<%= f.radio_button :age_eq, 1 %>
			<%= f.label :age, "子猫", {value: :子猫} %>
			<%= f.radio_button :age_eq, 2 %>
			<%= f.label :age, "成猫", {value: :成猫} %>
			<%= f.radio_button :age_eq, 3 %>
			<%= f.label :age, "老猫", {value: :老猫} %>
		</p>
	</div>

	<div class="field is-grouped">
		<%= f.label "種類", class: "subtitle is-6" %>
		<p class="control">
			<div class="select">
				<%= f.select :type_eq, Post.types, :include_blank => '指定しない' %>
			</div>
		</p>
	</div>

	<div class="actions">
		<%= f.submit "検索", class: "button is-info" %>
	</div>

	<% end %>
</div>

app/views/posts/edit.html.erb
<h1 class="title is-1 has-text-primary">投稿内容変更ページ</h1>

<!-- エラーあれば件数を表示 -->
<% if @post.errors.any? %>
<div id="error_explanation">
  <h2><%= @post.errors.count %>件のエラーが発生しました。</h2>
  <ul>
    <% @post.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="box">
  <%= form_for(@post) do |f| %>

  <div class="field">
    <%= attachment_image_tag @post, :image, :fill, 700, 450, fallback: "no_image.jpg" %>
    <%= f.attachment_field :image %>
  </div>

  <div class="field">
    <p class="control">
      <%= f.label "投稿タイトル" %>
      <%= f.text_field :title, autofocus: true, class: "input", placeholder: "（例：ボールが大好き！）", autocomplete: "title" %>
    </p>
  </div>

  <div class="field">
    <p class="control">
      <%= f.label "投稿内容" %>
      <%= f.text_area :content, autofocus: true, class: "input", placeholder: "（例：ボールを追いかけるウチのミイちゃんです。）", autocomplete: "content" %>
    </p>
  </div>

  <div class="field">
    <%= f.label "性別" %>
    <p class="control">
      <%= f.radio_button :sex, :未選択 %>
      <%= f.label :sex, "未選択", {value: :未選択} %>
      <%= f.radio_button :sex, :オス %>
      <%= f.label :sex, "オス", {value: :オス} %>
      <%= f.radio_button :sex, :メス %>
      <%= f.label :sex, "メス", {value: :メス} %>
    </p>
  </div>

  <div class="field">
    <%= f.label "年齢" %>
    <p class="control">
      <%= f.radio_button :age, :未選択 %>
      <%= f.label :age, "未選択", {value: :未選択} %>
      <%= f.radio_button :age, :子猫 %>
      <%= f.label :age, "子猫", {value: :子猫} %>
      <%= f.radio_button :age, :成猫 %>
      <%= f.label :age, "成猫", {value: :成猫} %>
      <%= f.radio_button :age, :老猫 %>
      <%= f.label :age, "老猫", {value: :老猫} %>
    </p>
  </div>

  <div class="field">
    <%= f.label "種類" %>
    <p class="control">
      <div class="select">
        <%= f.select :type, Post.types.keys, {} %>
      </div>
    </p>
  </div>

  <div class="actions">
    <%= f.submit "変更内容を保存する", class: "button is-success" %>
  </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<h1 class="title is-1 has-text-primary">投稿一覧ページ</h1>

<!-- 検索フォーム -->
<%= render 'posts/search_form', q: @q %>

<!-- 投稿一覧or検索結果表示 -->
<%= render 'posts/index', posts: @posts %>

<%= paginate @posts, class: "paginate" %>

app/views/posts/new.html.erb
<h1 class="title is-1 has-text-primary">新規投稿ページ</h1>

<!-- エラーあれば件数を表示 -->
<% if @post.errors.any? %>
<div id="error_explanation">
  <h2><%= @post.errors.count %>件のエラーが発生しました。</h2>
  <ul>
    <% @post.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="box">
  <%= form_for(@post, url: posts_path) do |f| %>

  <div class="field">
    <%= attachment_image_tag @post, :image, :fill, fallback: "no_image.jpg", size:'300x200' %>
    <%= f.attachment_field :image %>
  </div>

  <div class="field">
    <p class="control">
      <%= f.label "投稿タイトル" %>
      <%= f.text_field :title, autofocus: true, class: "input", placeholder: "（例：ボールが大好き！）", autocomplete: "title" %>
    </p>
  </div>

  <div class="field">
    <p class="control">
      <%= f.label "投稿内容" %>
      <%= f.text_area :content, autofocus: true, class: "input", placeholder: "（例：ボールを追いかけるウチのミイちゃんです。）", autocomplete: "content" %>
    </p>
  </div>

  <div class="field">
   <%= f.label "性別" %>
   <p class="control">
     <%= f.radio_button :sex, :未選択 %>
     <%= f.label :sex, "未選択", {value: :未選択} %>
     <%= f.radio_button :sex, :オス %>
     <%= f.label :sex, "オス", {value: :オス} %>
     <%= f.radio_button :sex, :メス %>
     <%= f.label :sex, "メス", {value: :メス} %>
   </p>
 </div>

 <div class="field">
   <%= f.label "年齢" %>
   <p class="control">
     <%= f.radio_button :age, :未選択 %>
     <%= f.label :age, "未選択", {value: :未選択} %>
     <%= f.radio_button :age, :子猫 %>
     <%= f.label :age, "子猫", {value: :子猫} %>
     <%= f.radio_button :age, :成猫 %>
     <%= f.label :age, "成猫", {value: :成猫} %>
     <%= f.radio_button :age, :老猫 %>
     <%= f.label :age, "老猫", {value: :老猫} %>
   </p>
 </div>

 <div class="field">
   <%= f.label "種類" %>
   <p class="control">
     <div class="select">
       <%= f.select :type, Post.types.keys, {} %>
     </div>
   </p>
 </div>

 <div class="actions">
  <%= f.submit "投稿する" , class: "button is-success" %>
</div>

<% end %>
</div>

app/views/posts/show.html.erb
<h1 class="title is-1 has-text-primary">投稿詳細ページ</h1>

<div class="tile is-ancestor">
	<div class="tile is-parent">
		<!-- 画像表示 -->
		<div class="tile is-child box">
			<%= attachment_image_tag @post, :image, :fill, 700, 450, fallback: "no_image.jpg" %>
			<div class="tag-box">
				<% @post.tags.each do |tag| %>
				  <span class="label"><%= tag.name %></span>
				<% end %>
			</div>
			<hr>
			<!-- ログイン時のみいいねボタン表示 -->
			<% if user_signed_in? %>
			<div id="post-<%= @post.id %>">
				<%= render partial: "posts/favorite", locals: { post: @post } %>
			</div>
			<% end %>
			<!-- 投稿情報 -->
			<span class="subtitle is-6">投稿タイトル</span>
			<p><%= @post.title %></p>
			<span class="subtitle is-6">内容</span>
			<p><%= @post.content %></p>
			<span class="subtitle is-6">猫情報</span>
			<p><%= @post.sex %> ／ <%= @post.age %> ／ <%= @post.type %></p>
			<span class="subtitle is-6">投稿日</span>
			<p><%= @post.created_at.strftime('%Y/%m/%d') %></p>
			<!-- ログインしている会員の場合のみ編集と削除ボタンを表示 -->
			<% if @post.user == current_user %>
			<hr>
			<%= link_to "内容を変更する", edit_post_path(@post), class: "button is-success" %>
			<%= link_to "この投稿を削除する", post_path(@post), class: "button is-danger", method: :delete, data:{confirm: "本当に消しますか？"} %>
			<% end %>
		</div>
	</div>
	<div class="tile is-parent">
		<div class="tile is-child">
			<!-- 投稿者情報ここから -->
			<h4 class="subtitle is-3">投稿者情報</h4>
			<span class="subtitle is-6">ハンドルネーム</span>
			<p><%= link_to @post.user.handle_name, user_path(@post.user.id) %></p>
			<span class="subtitle is-6">自己紹介文</span>
			<p><%= @post.user.profile %></p>
			<span class="subtitle is-6">住所</span>
			<p><%= @post.user.prefecture %></p>
			<!-- 投稿者情報ここまで -->
			<hr>
			<!-- コメント欄ここから -->
			<h4 class="subtitle is-3">コメント欄</h4>
			<div id="comment_<%= @post.id %>">
				<%= render 'posts/comment', post_comments: @post.post_comments %>
			</div>
			<!-- ログイン時はコメント入力フォーム表示 -->
			<% if user_signed_in? %>
			<div class="comment_form">
				<%= form_with(model: [@post, @post_comment], remote: true) do |f| %>
				<%= f.text_area :comment, class: "textarea", placeholder: "この投稿への感想などはこちらへどうぞ！" %>
				<%= f.submit "コメントを送信する", class: "button is-info is-pulled-right" %>
				<% end %>
			</div>
			<!-- 未ログイン時はメッセージを表示 -->
			<% else %>
			<div class="box">
				<p>
					コメントの投稿は会員のみが利用できます。<br>
					新規会員登録は<%= link_to "こちら", "/users/sign_up" %>から。
				</p>
			</div>
			<% end %>
			<!-- コメント欄ここまで -->
		</div>
	</div>
</div>